import {
  FaCode,
  FaMicrochip,
  FaPeopleGroup,
  FaCloud,
  FaLaptopCode,
  FaCheckDouble,
  FaAws,
  FaCss3,
} from "react-icons/fa6";
import {
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiReact,
  SiNextdotjs,
  SiNestjs,
  SiFastify,
  SiAngular,
  SiHtml5,
  SiTailwindcss,
  SiChakraui,
  SiPhp,
  SiPython,
  SiTerraform,
  SiDocker,
  SiGithubactions,
  SiServerless,
  SiCloudflare,
  SiKubernetes,
  SiLangchain,
  SiPostgresql,
  SiRedis,
  SiSupabase,
  SiVitest,
  SiJest,
  SiTestinglibrary,
  SiCypress,
  SiGit,
  SiMongodb,
} from "react-icons/si";
import { TbLambda, TbPrompt, TbSql } from "react-icons/tb";
import { TiCloudStorage } from "react-icons/ti";
import { GrTest } from "react-icons/gr";
import { MdIntegrationInstructions } from "react-icons/md";
import { DiScrum } from "react-icons/di";
import { PiKanban } from "react-icons/pi";
import type { CategoriaHabilidade } from "@/types/habilidade";
import { cores } from "@/lib/tema/tokens";

export const STUB_HABILIDADES: CategoriaHabilidade[] = [
  {
    id: "arquitetura",
    titulo: "Arquitetura & Clean Code",
    descricao:
      "Microsserviços escaláveis, Hexagonal Architecture, NestJS, Node.js, Fastify e React.",
    cor: cores.secundaria.claro,
    corFundo: cores.secundaria.sutil,
    corBorda: "rgba(99, 102, 241, 0.35)",
    icone: FaCode,
    iconeBg: cores.secundaria.sutil,
    iconeColor: cores.secundaria.DEFAULT,
    habilidades: [
      { nome: "Microsserviços" },
      { nome: "Hexagonal Architecture" },
      { nome: "Clean Architecture" },
      { nome: "Domain-Driven Design" },
      { nome: "Event-Driven Architecture" },
      { nome: "CQRS" },
      { nome: "Design Patterns" },
      { nome: "SOLID" },
      { nome: "API REST" },
      { nome: "GraphQL" },
      { nome: "gRPC" },
    ],
  },
  {
    id: "desenvolvimento",
    titulo: "Desenvolvimento",
    descricao:
      "Stack moderna com TypeScript, React, Node.js e ferramentas de alta produtividade.",
    cor: cores.sucesso.claro,
    corFundo: cores.sucesso.sutil,
    corBorda: "rgba(34, 197, 94, 0.35)",
    icone: FaLaptopCode,
    iconeBg: cores.sucesso.sutil,
    iconeColor: cores.sucesso.claro,
    habilidades: [
      { nome: "TypeScript", icone: SiTypescript },
      { nome: "JavaScript", icone: SiJavascript },
      { nome: "Node.js", icone: SiNodedotjs },
      { nome: "React", icone: SiReact },
      { nome: "Next.js", icone: SiNextdotjs },
      { nome: "NestJS", icone: SiNestjs },
      { nome: "Fastify", icone: SiFastify },
      { nome: "Angular", icone: SiAngular },
      { nome: "HTML5", icone: SiHtml5 },
      { nome: "CSS3", icone: FaCss3 },
      { nome: "Tailwind CSS", icone: SiTailwindcss },
      { nome: "Chakra UI", icone: SiChakraui },
      { nome: "PHP", icone: SiPhp },
      { nome: "Python", icone: SiPython },
    ],
  },
  {
    id: "cloud-devops",
    titulo: "Cloud & DevOps",
    descricao:
      "Ecossistemas nativos em nuvem (AWS Serverless, Terraform) com pipelines automatizados.",
    cor: cores.info.claro,
    corFundo: cores.info.sutil,
    corBorda: "rgba(6, 182, 212, 0.35)",
    icone: FaCloud,
    iconeBg: cores.info.sutil,
    iconeColor: cores.info.claro,
    habilidades: [
      { nome: "AWS", icone: FaAws },
      { nome: "Lambda", icone: TbLambda },
      { nome: "S3", icone: TiCloudStorage },
      { nome: "CloudFront" },
      { nome: "Terraform", icone: SiTerraform },
      { nome: "Docker", icone: SiDocker },
      { nome: "CI/CD" },
      { nome: "GitHub Actions", icone: SiGithubactions },
      { nome: "Serverless", icone: SiServerless },
      { nome: "Cloudflare", icone: SiCloudflare },
      { nome: "Kubernetes", icone: SiKubernetes },
    ],
  },
  {
    id: "ia-dados",
    titulo: "Estratégia de IA & Dados",
    descricao:
      "Inteligência artificial aplicada, automação com LLMs e bancos de dados de alta performance.",
    cor: cores.primaria.claro,
    corFundo: cores.primaria.sutil,
    corBorda: cores.primaria.borda,
    icone: FaMicrochip,
    iconeBg: cores.primaria.sutil,
    iconeColor: cores.primaria.claro,
    habilidades: [
      { nome: "LLMs" },
      { nome: "RAG" },
      { nome: "Prompt Engineering", icone: TbPrompt },
      { nome: "LangChain", icone: SiLangchain },
      { nome: "Embeddings" },
      { nome: "Automação com IA" },
      { nome: "SQL", icone: TbSql },
      { nome: "MongoDB", icone: SiMongodb },
      { nome: "PostgreSQL", icone: SiPostgresql },
      { nome: "Redis", icone: SiRedis },
      { nome: "Supabase", icone: SiSupabase },
    ],
  },
  {
    id: "comunicacao-lideranca",
    titulo: "Liderança & Comunicação",
    descricao:
      "Desenvolvimento de pessoas, mentoria técnica e alinhamento entre engenharia e negócio.",
    cor: cores.alerta.claro,
    corFundo: cores.alerta.sutil,
    corBorda: "rgba(234, 179, 8, 0.35)",
    icone: FaPeopleGroup,
    iconeBg: cores.alerta.sutil,
    iconeColor: cores.alerta.claro,
    habilidades: [
      { nome: "Mentoria Técnica" },
      { nome: "Liderança de Squads" },
      { nome: "Comunicação Assertiva" },
      { nome: "Code Review" },
      { nome: "Pair Programming" },
      { nome: "Facilitação" },
      { nome: "Gestão de Conhecimento" },
      { nome: "Tech Talks" },
    ],
  },
  {
    id: "qualidade",
    titulo: "Qualidade & Processos",
    descricao:
      "TDD, testes automatizados e processos ágeis para entregas confiáveis.",
    cor: cores.erro.claro,
    corFundo: cores.erro.sutil,
    corBorda: "rgba(239, 68, 68, 0.35)",
    icone: FaCheckDouble,
    iconeBg: cores.erro.sutil,
    iconeColor: cores.erro.claro,
    habilidades: [
      { nome: "TDD" },
      { nome: "Testes Unitários", icone: GrTest },
      { nome: "Testes de Integração", icone: MdIntegrationInstructions },
      { nome: "Vitest", icone: SiVitest },
      { nome: "Jest", icone: SiJest },
      { nome: "Testing Library", icone: SiTestinglibrary },
      { nome: "Cypress", icone: SiCypress },
      { nome: "Git Flow", icone: SiGit },
      { nome: "Conventional Commits" },
      { nome: "Scrum", icone: DiScrum },
      { nome: "Kanban", icone: PiKanban },
    ],
  },
];
